CREATE DATABASE IF NOT EXISTS syncdb;
USE syncdb;

CREATE TABLE IF NOT EXISTS users (
  __id CHAR(36) PRIMARY KEY,
  name VARCHAR(200),
  email VARCHAR(200),
  role VARCHAR(100),
  __version INT DEFAULT 1,
  __last_modified_utc TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS change_log (
  id CHAR(36) PRIMARY KEY,
  table_name VARCHAR(100),
  pk CHAR(36),
  op ENUM('INSERT','UPDATE','DELETE','UPSERT') DEFAULT 'UPSERT',
  row_data JSON,
  source VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  processed BOOLEAN DEFAULT FALSE,
  processed_at TIMESTAMP NULL
);
